### ISSUE TITLE
RPGme Incompatability

### ISSUE THREAD

**Issue by UberPilot** [Jessy1237/DwarfCraft_premerge#33]
There seems to be an issue between RPGme and this plugin. RPGme works fine when DwarfCraft is disabled, but the features from that plugin no longer work when it is enabled. I'm not sure which plugin is causing this issue, but DwarfCraft features work fine with RPGme, but not the other way around, so I'm assuming that DwarfCraft is overriding some core functionality of RPGme. Is there a way to create a compatability patch or something of that sort?

**Comment by Jessy1237** [comment]
Yes I'll look into it but do you know specifically what features break in rpgme?

**Comment by UberPilot** [comment]
Powertools are the main thing that breaks, and one of the main features of RPGme. I'd assume that it was the instabreak/chance effects on certain blocks in DwarfCraft, but I can't say for sure.

Also, I'm getting an exception when running /removetrainer, and can't remove any DwarfCraft NPCs. It's most likely unrelated to the incompatibility, but I figured that I'd bring that up as well.

PS: Thanks for the quick response!

**Comment by Jessy1237** [comment]
So the issue between RPGMe and DwarfCraft is event Priorities. In RPGMe it is specified that the BlockBreakEvent priority for the listener is on Monitor so it is of lower priority of that of DwarfCraft. The plugin developer shouldn't be really altering anything in the event anyway with the priority set to monitor as its only meant to be used for monitoring the event. So if you want this fixed i'd suggest sending a issue tracker to RPGMe stating if possible for them to change the event priorities to "HIGHEST" as DwarfCraft is set to "HIGH" due to the fact that it heavily relies on this event. I however don't really have any intentions on lowering the event priority on my side as of yet.

Side Note: the remove trainer issue is fixed in the lasted commit.
